### ISSUE TITLE
IAM permissions

### ISSUE THREAD

**Issue by erikbergsma** [markcaudill/haproxy-autoscale#16]
maybe something for the next release?
- An example minimal IAM policy, so that the key + secret can only be used for the functionality of this script
- IAM role / credential file support (since you can see the paramaters given on the system if you do a "ps auxf")

**Comment by markcaudill** [comment]
I'm rolling the second item (IAM role / credential file support) into an issue that will involve allowing all configurations to be specified in a file rather than on the command line.
