### ISSUE TITLE
integration with aqueduct

### ISSUE THREAD

**Issue by hems** [markcaudill/haproxy-autoscale#19]
Hello Markcaudill, i think you might be interested in knowing https://github.com/PearsonEducation/thalassa-aqueduct it will basically give you a web interface and an API in order to manage your haproxy configuration / reload.

this way your services cause just register/unregister by simply posting to an http endpoint..

**Comment by markcaudill** [comment]
This looks neat but outside of the scope of this project. If you happen to come up with some integration and think it should be documented here, let me know and I'll review it. Thanks.
