### ISSUE TITLE
401 Unauthorized from AWS

### ISSUE THREAD

**Issue by justinperkins** [markcaudill/haproxy-autoscale#20]
This just suddenly started happening without anything changing on our end. Oddly enough, we run this lib both in a staging environment and prod, but only the prod server stopped working. Both servers have the exact same configuration, running boto (2.35.1).
```
>>> from boto.ec2 import EC2Connection, get_region
>>> conn=EC2Connection(aws_access_key_id='KEY ID', aws_secret_access_key='KEY SECRET')
>>> conn.get_all_regions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 3477, in get_all_regions
    [('item', RegionInfo)], verb='POST')
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1185, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 401 Unauthorized
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to validate the provided access credentials</Message></Error></Errors><RequestID>53deb9bb-b3f5-484c-82aa-a0cb60c2be0a</RequestID></Response>
```

**Comment by markcaudill** [comment]
I know I'm really late in responding to this, but can you provide some more detail? Does this issue persist or was it a problem resolved by updating Boto?

**Comment by justinperkins** [comment]
Hey Mark, thanks for the reply. I forgot I submitted this issue. It's due to time drift on the server, running an ntp update resolves the issue. Be cool if AWS gave a more helpful response, but there's no issue with the autoscale library for sure.

**Comment by markcaudill** [comment]
Thanks!
