### ISSUE TITLE
Help with execute!

### ISSUE THREAD

**Issue by svillegasc** [markcaudill/haproxy-autoscale#25]
Hi, Forgive my ignorance, i don't know how to run update-haproxy.py with their params...
help me!...

Thanks

**Comment by markcaudill** [comment]
Ah ok. Check out the [README](https://github.com/markcaudill/haproxy-autoscale/blob/master/README.md#usage) and scroll down to the example that shows how to run it from the command line. Is this what you're asking about?

**Comment by svillegasc** [comment]
Yes, that i did, but dont know that is the parameter 'tomcat-servers'...
what should use here?

Thanks your for answering so quickly.

**Comment by markcaudill** [comment]
In the example in the readme, 'webheads' and 'tomcat-servers' are just examples of values being passed to the `--security-group` parameter. So what happens is that ever RUNNING instance in each of those specified availability groups gets added to the VIP. You should replace 'webheads' and 'tomcat-servers' with the name(s) of the security group(s) you want to have load balanced.
