### ISSUE TITLE
Wrong key/secret doesn't exit; empty instances list would generate empty cfg and reload and ruin the env.

### ISSUE THREAD

**Issue by IronCore864** [markcaudill/haproxy-autoscale#29]
Good script. Thanks a lot first. We are planning to use it in production.

But I met the issues mentioned in the title. I'm not sure if this is by design, or a bug.

1. For example, you have a test environment, and a production one. After you test it, you run it on prod, but somehow you forget to update the key/secret, and boto.exception.EC2ResponseError is thrown, but since the program continues, a new conf with empty instance list would be generated and reloaded, and the environment won't work anymore.
2. Or if the instance list from a group is empty, it would still generate a new conf with empty instance list.

My five cents:
- Maybe we can add a new option, like IS_PRODUCTION, which if is true, don't generate empty conf and definitely don't reload the empty conf.
- Or add some checks in generate_haproxy_config to test if instances is empty or not. If empty, give some warnings and don't reload.
- Multiple ways to improve this. But again, I'm not sure if this is a bug or by design. Maybe you want to generate a conf no matter there is instance or not.

If I were you, I would exit directly in case of EC2ResponseError, and in case of empty instances list, give warning and don't reload.

What do you think? If you agree but don't have time I can contribute a PR for this.

**Comment by markcaudill** [comment]
Hey thanks for your ideas! You're correct in that I don't really maintain this project anymore other than to support and merge PRs. Definitely feel free to fork and maintain something that works best for you in production. I'd be more than happy to review (and hopefully merge) any upstream contributions you're willing to provide! The most important thing is to not break backwards compatibility. I think a number of people *do* use this in production already and it would be bad for them to do a `git pull` and unwittingly get a version that causes an outage for them.

Thanks again for your interest!

**Comment by IronCore864** [comment]
I'll close this issue now and create a PR for you to review. Thanks!
